Clean up ml_api dockerfiles with hadolint
Merge commands

move some pip packages to requirements.txt

diff --git a/ml_api/Dockerfile b/ml_api/Dockerfile
--- a/ml_api/Dockerfile
+++ b/ml_api/Dockerfile
@@ -2,11 +2,12 @@ FROM thespaghettidetective/ml_api_base:1.3
 WORKDIR /app
 EXPOSE 3333
 
-ADD . /app
-RUN pip install --upgrade pip
-RUN pip install -r requirements.txt
+COPY . /app
+RUN pip install --upgrade --no-cache-dir pip==23.3.2 \
+    && pip install --no-cache-dir -r requirements.txt
 
-RUN echo 'Downloading the latest failure detection AI model in Darknet format...'
-RUN wget -O model/model-weights.darknet $(cat model/model-weights.darknet.url | tr -d '\r')
-RUN echo 'Downloading the latest failure detection AI model in ONNX format...'
-RUN wget -O model/model-weights.onnx $(cat model/model-weights.onnx.url | tr -d '\r')
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+RUN echo 'Downloading the latest failure detection AI model in Darknet format...' \
+    && wget --progress=dot:giga -O model/model-weights.darknet -i model/model-weights.darknet.url
+RUN echo 'Downloading the latest failure detection AI model in ONNX format...' \
+    && wget --progress=dot:giga -O model/model-weights.onnx -i model/model-weights.onnx.url
